### PR TITLE
feat: Add support for querying subfields with GraphQL.

### PR DESCRIPTION
**Pull request by peaffenzeller**

### CODE REVIEW

**Comment by peaffenzeller** [comment]
Added support to query for subfields with GraphQL.
Closes #69

I hope everything makes sense, never touched a Craft plugin before or did something GraphQL-related except for querying stuff...

Tested everything in the project I'm currently working on. We are using Linkit fields for e.g. buttons there. A couple of screenshots of what the result looks like are attached. (GraphiQL explorer, query and result)

Screenshot 2021-09-16 at 16 20 22
Screenshot 2021-09-16 at 16 20 41
Screenshot 2021-09-16 at 16 21 07

**Comment by peaffenzeller** [comment]
@shornuk @ben-callaway @angrybrad @samhibberd would be awesome if one of you could take a look!
for now, it's not too pressing for me, but we will need proper GraphQL support sometime soon... :)

**Comment by peaffenzeller** [comment]
@shornuk @ben-callaway @angrybrad @samhibberd anybody? please?

**Comment by internetztube** [comment]
Any updates? @ben-callaway @samhibberd

**Comment by samhibberd** [comment]
@internetztube if you take a look at #96, we have added support in an upcoming release.

**Pull request closed without merging**
