### PR TITLE
Added support for cross-site entry linking.

### LINKED ISSUE #84: Allow to select entries from other sites in entry picker not working
Follow up ticket to https://github.com/presseddigital/linkit/issues/72

After the fix from issue 72 I now have a dropdown with my multisites in the linkit entry picker.
When i select an other site in this dropdown, the select options (entries to choose from) do not change. So unfortunately it is still not possible to select entries from other multisites.

It would be great if you could check that again, thank you!

### PR DESCRIPTION
**Pull request by ghost**
Fixes #84 

Added siteId to field settings when selecting an entry.

### CODE REVIEW

**Comment by abryrath** [comment]
Is there anything the community can do to move this PR along? The issue has been open since December. Until this is merged, we are forced to use @renzo-s 's fork while we are still paying for updates upstream.

**Comment by samhibberd** [comment]
So sorry for the silence, we have literally just hit the launch button on what has been an all consuming 18 month project for our entire team, lucky that our partners are still talking to us all, let alone everyone else!

Anyway we should finally have some time to give our plugins some well overdue attention, please bear with us whilst we get our lives back on track!!!

Thanks.

**Comment by WHITE-developer** [comment]
So, any update on this ;-) ?

**Comment by FrDH** [comment]
So, any update on this :( ?

**Comment by ben-callaway** [comment]
Thanks, looking at this now - sorry for the delay on this one.

**Comment by mnlmaier** [comment]
Hi @renzo-s, I am not counting on the team merging this PR anytime soon, so I've patched in your changes which at first glance improves the problem :) Thanks for that! However, when saving the link field with a selected entry from another site, nothing gets rendered in the actual template.

Are there any specifics which I have to keep in mind for the whole thing to work?

**Comment by samhibberd** [comment]
Hey folks, we were hoping to have this added / fixed as a part of the upcoming craft 4/5 updates, but we are running into issues with supporting our custom eager-loading mapping. Will be next on the list once c5 is out.

**Pull request closed without merging**
